/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Company model module.
* @module model/Company
* @version 1.0
*/
export default class Company {
    /**
    * Constructs a new <code>Company</code>.
    * @alias module:model/Company
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Company} obj Optional instance to populate.
    * @return {module:model/Company} The populated <code>Company</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Company();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = ApiClient.convertToType(data['abbreviation'], 'String');
            }
            if (data.hasOwnProperty('alias')) {
                obj['alias'] = ApiClient.convertToType(data['alias'], 'String');
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Number');
            }
            if (data.hasOwnProperty('category_name')) {
                obj['category_name'] = ApiClient.convertToType(data['category_name'], 'String');
            }
        }
        return obj;
    }

    /**
    * Company Id
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * The name of the company
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The company's abbreviation
    * @member {String} abbreviation
    */
    'abbreviation' = undefined;
    /**
    * The company's alias
    * @member {String} alias
    */
    'alias' = undefined;
    /**
    * Company category Id
    * @member {Number} category_id
    */
    'category_id' = undefined;
    /**
    * Category name
    * @member {String} category_name
    */
    'category_name' = undefined;




}
