/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DevNote model module.
* @module model/DevNote
* @version 1.0
*/
export default class DevNote {
    /**
    * Constructs a new <code>DevNote</code>.
    * @alias module:model/DevNote
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DevNote</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DevNote} obj Optional instance to populate.
    * @return {module:model/DevNote} The populated <code>DevNote</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DevNote();
                        
            
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }

    /**
    * Date submitted
    * @member {Date} date
    */
    'date' = undefined;
    /**
    * Note
    * @member {String} note
    */
    'note' = undefined;




}
