/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DisciplineUpdate model module.
* @module model/DisciplineUpdate
* @version 1.0
*/
export default class DisciplineUpdate {
    /**
    * Constructs a new <code>DisciplineUpdate</code>.
    * @alias module:model/DisciplineUpdate
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DisciplineUpdate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DisciplineUpdate} obj Optional instance to populate.
    * @return {module:model/DisciplineUpdate} The populated <code>DisciplineUpdate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DisciplineUpdate();
                        
            
            if (data.hasOwnProperty('inspection_type')) {
                obj['inspection_type'] = ApiClient.convertToType(data['inspection_type'], 'String');
            }
            if (data.hasOwnProperty('discipline')) {
                obj['discipline'] = ApiClient.convertToType(data['discipline'], 'String');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('chassis')) {
                obj['chassis'] = ApiClient.convertToType(data['chassis'], 'String');
            }
            if (data.hasOwnProperty('inspection_time')) {
                obj['inspection_time'] = ApiClient.convertToType(data['inspection_time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The type of inspection
    * @member {String} inspection_type
    */
    'inspection_type' = undefined;
    /**
    * The inspection discipline
    * @member {String} discipline
    */
    'discipline' = undefined;
    /**
    * The vehicle inspected
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * The chassis inspected
    * @member {String} chassis
    */
    'chassis' = undefined;
    /**
    * The time of the inspection
    * @member {Date} inspection_time
    */
    'inspection_time' = undefined;




}
