/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Driver from './Driver';
import DriverSummaryByPrincipalRaceID from './DriverSummaryByPrincipalRaceID';
import DriverSummaryBySeason from './DriverSummaryBySeason';
import DriverSummaryByTrack from './DriverSummaryByTrack';
import DriverSummaryByTrackType from './DriverSummaryByTrackType';

/**
* The DriverSummary model module.
* @module model/DriverSummary
* @version 1.0
*/
export default class DriverSummary {
    /**
    * Constructs a new <code>DriverSummary</code>.
    * @alias module:model/DriverSummary
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DriverSummary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DriverSummary} obj Optional instance to populate.
    * @return {module:model/DriverSummary} The populated <code>DriverSummary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DriverSummary();
                        
            
            if (data.hasOwnProperty('Driver')) {
                obj['Driver'] = Driver.constructFromObject(data['Driver']);
            }
            if (data.hasOwnProperty('Summary_ByPrincipalRaceIDs')) {
                obj['Summary_ByPrincipalRaceIDs'] = ApiClient.convertToType(data['Summary_ByPrincipalRaceIDs'], [DriverSummaryByPrincipalRaceID]);
            }
            if (data.hasOwnProperty('Summary_BySeason')) {
                obj['Summary_BySeason'] = DriverSummaryBySeason.constructFromObject(data['Summary_BySeason']);
            }
            if (data.hasOwnProperty('Summary_ByTracks')) {
                obj['Summary_ByTracks'] = ApiClient.convertToType(data['Summary_ByTracks'], [DriverSummaryByTrack]);
            }
            if (data.hasOwnProperty('Summary_ByTrackTypes')) {
                obj['Summary_ByTrackTypes'] = ApiClient.convertToType(data['Summary_ByTrackTypes'], [DriverSummaryByTrackType]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Driver} Driver
    */
    'Driver' = undefined;
    /**
    * Principal race summaries
    * @member {Array.<module:model/DriverSummaryByPrincipalRaceID>} Summary_ByPrincipalRaceIDs
    */
    'Summary_ByPrincipalRaceIDs' = undefined;
    /**
    * @member {module:model/DriverSummaryBySeason} Summary_BySeason
    */
    'Summary_BySeason' = undefined;
    /**
    * Track summaries
    * @member {Array.<module:model/DriverSummaryByTrack>} Summary_ByTracks
    */
    'Summary_ByTracks' = undefined;
    /**
    * Track type summaries
    * @member {Array.<module:model/DriverSummaryByTrackType>} Summary_ByTrackTypes
    */
    'Summary_ByTrackTypes' = undefined;




}
