/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Driver model module.
* @module model/Driver
* @version 1.0
*/
export default class Driver {
    /**
    * Constructs a new <code>Driver</code>.
    * @alias module:model/Driver
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Driver</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Driver} obj Optional instance to populate.
    * @return {module:model/Driver} The populated <code>Driver</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Driver();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('date_of_birth')) {
                obj['date_of_birth'] = ApiClient.convertToType(data['date_of_birth'], 'Date');
            }
            if (data.hasOwnProperty('date_of_death')) {
                obj['date_of_death'] = ApiClient.convertToType(data['date_of_death'], 'Date');
            }
            if (data.hasOwnProperty('hometown_city')) {
                obj['hometown_city'] = ApiClient.convertToType(data['hometown_city'], 'String');
            }
            if (data.hasOwnProperty('hometown_state')) {
                obj['hometown_state'] = ApiClient.convertToType(data['hometown_state'], 'String');
            }
            if (data.hasOwnProperty('hometown_country')) {
                obj['hometown_country'] = ApiClient.convertToType(data['hometown_country'], 'String');
            }
            if (data.hasOwnProperty('resides_city')) {
                obj['resides_city'] = ApiClient.convertToType(data['resides_city'], 'String');
            }
            if (data.hasOwnProperty('resides_state')) {
                obj['resides_state'] = ApiClient.convertToType(data['resides_state'], 'String');
            }
            if (data.hasOwnProperty('resides_country')) {
                obj['resides_country'] = ApiClient.convertToType(data['resides_country'], 'String');
            }
            if (data.hasOwnProperty('series_1_rookie_year')) {
                obj['series_1_rookie_year'] = ApiClient.convertToType(data['series_1_rookie_year'], 'Number');
            }
            if (data.hasOwnProperty('series_2_rookie_year')) {
                obj['series_2_rookie_year'] = ApiClient.convertToType(data['series_2_rookie_year'], 'Number');
            }
            if (data.hasOwnProperty('series_3_rookie_year')) {
                obj['series_3_rookie_year'] = ApiClient.convertToType(data['series_3_rookie_year'], 'Number');
            }
            if (data.hasOwnProperty('hobbies')) {
                obj['hobbies'] = ApiClient.convertToType(data['hobbies'], 'String');
            }
        }
        return obj;
    }

    /**
    * Id
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * Name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Date of birth
    * @member {Date} date_of_birth
    */
    'date_of_birth' = undefined;
    /**
    * Date of death
    * @member {Date} date_of_death
    */
    'date_of_death' = undefined;
    /**
    * The driver's hometown
    * @member {String} hometown_city
    */
    'hometown_city' = undefined;
    /**
    * The driver's home state
    * @member {String} hometown_state
    */
    'hometown_state' = undefined;
    /**
    * The driver's home country
    * @member {String} hometown_country
    */
    'hometown_country' = undefined;
    /**
    * The city where the driver resides
    * @member {String} resides_city
    */
    'resides_city' = undefined;
    /**
    * The state where the driver resides
    * @member {String} resides_state
    */
    'resides_state' = undefined;
    /**
    * The country where the driver resides
    * @member {String} resides_country
    */
    'resides_country' = undefined;
    /**
    * The driver's rookie year in series 1
    * @member {Number} series_1_rookie_year
    */
    'series_1_rookie_year' = undefined;
    /**
    * The driver's rookie year in series 2
    * @member {Number} series_2_rookie_year
    */
    'series_2_rookie_year' = undefined;
    /**
    * The driver's rookie year in series 3
    * @member {Number} series_3_rookie_year
    */
    'series_3_rookie_year' = undefined;
    /**
    * The driver's hobbies
    * @member {String} hobbies
    */
    'hobbies' = undefined;




}
