/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Feedback model module.
* @module model/Feedback
* @version 1.0
*/
export default class Feedback {
    /**
    * Constructs a new <code>Feedback</code>.
    * email address to contact you at
    * @alias module:model/Feedback
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Feedback</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Feedback} obj Optional instance to populate.
    * @return {module:model/Feedback} The populated <code>Feedback</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Feedback();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }

    /**
    * Email address to contact you at
    * @member {String} email
    */
    'email' = undefined;
    /**
    * Feedback for devs
    * @member {String} note
    */
    'note' = undefined;




}
