/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LapLeader model module.
* @module model/LapLeader
* @version 1.0
*/
export default class LapLeader {
    /**
    * Constructs a new <code>LapLeader</code>.
    * @alias module:model/LapLeader
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LapLeader</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LapLeader} obj Optional instance to populate.
    * @return {module:model/LapLeader} The populated <code>LapLeader</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LapLeader();
                        
            
            if (data.hasOwnProperty('start_lap')) {
                obj['start_lap'] = ApiClient.convertToType(data['start_lap'], 'Number');
            }
            if (data.hasOwnProperty('end_lap')) {
                obj['end_lap'] = ApiClient.convertToType(data['end_lap'], 'Number');
            }
            if (data.hasOwnProperty('laps_led')) {
                obj['laps_led'] = ApiClient.convertToType(data['laps_led'], 'Number');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
        }
        return obj;
    }

    /**
    * Start lap
    * @member {Number} start_lap
    */
    'start_lap' = undefined;
    /**
    * End lap
    * @member {Number} end_lap
    */
    'end_lap' = undefined;
    /**
    * Total laps led
    * @member {Number} laps_led
    */
    'laps_led' = undefined;
    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;




}
