/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NextGenSource model module.
* @module model/NextGenSource
* @version 1.0
*/
export default class NextGenSource {
    /**
    * Constructs a new <code>NextGenSource</code>.
    * @alias module:model/NextGenSource
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NextGenSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NextGenSource} obj Optional instance to populate.
    * @return {module:model/NextGenSource} The populated <code>NextGenSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NextGenSource();
                        
            
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} source_id
    */
    'source_id' = undefined;
    /**
    * Source name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Description
    * @member {String} description
    */
    'description' = undefined;
    /**
    * Vehicle Number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;




}
