/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The NextGenDatapoint model module.
* @module model/NextGenDatapoint
* @version 1.0
*/
export default class NextGenDatapoint {
    /**
    * Constructs a new <code>NextGenDatapoint</code>.
    * @alias module:model/NextGenDatapoint
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NextGenDatapoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NextGenDatapoint} obj Optional instance to populate.
    * @return {module:model/NextGenDatapoint} The populated <code>NextGenDatapoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NextGenDatapoint();
                        
            
            if (data.hasOwnProperty('datapoint_id')) {
                obj['datapoint_id'] = ApiClient.convertToType(data['datapoint_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * Datapoint Id
    * @member {String} datapoint_id
    */
    'datapoint_id' = undefined;
    /**
    * Name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Description
    * @member {String} description
    */
    'description' = undefined;




}
