/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The OpticalTrackingUTMOffset model module.
* @module model/OpticalTrackingUTMOffset
* @version 1.0
*/
export default class OpticalTrackingUTMOffset {
    /**
    * Constructs a new <code>OpticalTrackingUTMOffset</code>.
    * @alias module:model/OpticalTrackingUTMOffset
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OpticalTrackingUTMOffset</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OpticalTrackingUTMOffset} obj Optional instance to populate.
    * @return {module:model/OpticalTrackingUTMOffset} The populated <code>OpticalTrackingUTMOffset</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpticalTrackingUTMOffset();
                        
            
            if (data.hasOwnProperty('track_id')) {
                obj['track_id'] = ApiClient.convertToType(data['track_id'], 'Number');
            }
            if (data.hasOwnProperty('track_name')) {
                obj['track_name'] = ApiClient.convertToType(data['track_name'], 'String');
            }
            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], 'String');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
            if (data.hasOwnProperty('z')) {
                obj['z'] = ApiClient.convertToType(data['z'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Track Id
    * @member {Number} track_id
    */
    'track_id' = undefined;
    /**
    * Track Name
    * @member {String} track_name
    */
    'track_name' = undefined;
    /**
    * Zone
    * @member {String} zone
    */
    'zone' = undefined;
    /**
    * X Coordinate
    * @member {Number} x
    */
    'x' = undefined;
    /**
    * Y coordinate
    * @member {Number} y
    */
    'y' = undefined;
    /**
    * Z coordinate
    * @member {Number} z
    */
    'z' = undefined;




}
