/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The OwnerPoint model module.
* @module model/OwnerPoint
* @version 1.0
*/
export default class OwnerPoint {
    /**
    * Constructs a new <code>OwnerPoint</code>.
    * @alias module:model/OwnerPoint
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OwnerPoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OwnerPoint} obj Optional instance to populate.
    * @return {module:model/OwnerPoint} The populated <code>OwnerPoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OwnerPoint();
                        
            
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('playoff_points')) {
                obj['playoff_points'] = ApiClient.convertToType(data['playoff_points'], 'Number');
            }
            if (data.hasOwnProperty('playoff_rank')) {
                obj['playoff_rank'] = ApiClient.convertToType(data['playoff_rank'], 'Number');
            }
            if (data.hasOwnProperty('delta_leader')) {
                obj['delta_leader'] = ApiClient.convertToType(data['delta_leader'], 'Number');
            }
            if (data.hasOwnProperty('delta_next')) {
                obj['delta_next'] = ApiClient.convertToType(data['delta_next'], 'Number');
            }
            if (data.hasOwnProperty('starts')) {
                obj['starts'] = ApiClient.convertToType(data['starts'], 'Number');
            }
            if (data.hasOwnProperty('poles')) {
                obj['poles'] = ApiClient.convertToType(data['poles'], 'Number');
            }
            if (data.hasOwnProperty('wins')) {
                obj['wins'] = ApiClient.convertToType(data['wins'], 'Number');
            }
            if (data.hasOwnProperty('stage_1_wins')) {
                obj['stage_1_wins'] = ApiClient.convertToType(data['stage_1_wins'], 'Number');
            }
            if (data.hasOwnProperty('stage_2_wins')) {
                obj['stage_2_wins'] = ApiClient.convertToType(data['stage_2_wins'], 'Number');
            }
            if (data.hasOwnProperty('stage_3_wins')) {
                obj['stage_3_wins'] = ApiClient.convertToType(data['stage_3_wins'], 'Number');
            }
            if (data.hasOwnProperty('stage_points')) {
                obj['stage_points'] = ApiClient.convertToType(data['stage_points'], 'Number');
            }
            if (data.hasOwnProperty('playoff_race_wins')) {
                obj['playoff_race_wins'] = ApiClient.convertToType(data['playoff_race_wins'], 'Number');
            }
            if (data.hasOwnProperty('playoff_stage_wins')) {
                obj['playoff_stage_wins'] = ApiClient.convertToType(data['playoff_stage_wins'], 'Number');
            }
            if (data.hasOwnProperty('points_earned_this_race')) {
                obj['points_earned_this_race'] = ApiClient.convertToType(data['points_earned_this_race'], 'Number');
            }
            if (data.hasOwnProperty('playoff_points_earned_this_race')) {
                obj['playoff_points_earned_this_race'] = ApiClient.convertToType(data['playoff_points_earned_this_race'], 'Number');
            }
            if (data.hasOwnProperty('stage_points_earned_this_race')) {
                obj['stage_points_earned_this_race'] = ApiClient.convertToType(data['stage_points_earned_this_race'], 'Number');
            }
            if (data.hasOwnProperty('top5')) {
                obj['top5'] = ApiClient.convertToType(data['top5'], 'Number');
            }
            if (data.hasOwnProperty('top10')) {
                obj['top10'] = ApiClient.convertToType(data['top10'], 'Number');
            }
            if (data.hasOwnProperty('laps_led')) {
                obj['laps_led'] = ApiClient.convertToType(data['laps_led'], 'Number');
            }
            if (data.hasOwnProperty('dnf')) {
                obj['dnf'] = ApiClient.convertToType(data['dnf'], 'Number');
            }
            if (data.hasOwnProperty('made_playoffs')) {
                obj['made_playoffs'] = ApiClient.convertToType(data['made_playoffs'], 'Boolean');
            }
            if (data.hasOwnProperty('in_playoffs')) {
                obj['in_playoffs'] = ApiClient.convertToType(data['in_playoffs'], 'Boolean');
            }
            if (data.hasOwnProperty('highest_round')) {
                obj['highest_round'] = ApiClient.convertToType(data['highest_round'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Owner name
    * @member {String} owner
    */
    'owner' = undefined;
    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * Points position
    * @member {Number} position
    */
    'position' = undefined;
    /**
    * Total points
    * @member {Number} points
    */
    'points' = undefined;
    /**
    * Total playoff points
    * @member {Number} playoff_points
    */
    'playoff_points' = undefined;
    /**
    * Current playoff rank
    * @member {Number} playoff_rank
    */
    'playoff_rank' = undefined;
    /**
    * Number of points behind the leader
    * @member {Number} delta_leader
    */
    'delta_leader' = undefined;
    /**
    * Number of points behind the next position
    * @member {Number} delta_next
    */
    'delta_next' = undefined;
    /**
    * Number of starts this season
    * @member {Number} starts
    */
    'starts' = undefined;
    /**
    * Number of times the pole position was earned
    * @member {Number} poles
    */
    'poles' = undefined;
    /**
    * Total race wins
    * @member {Number} wins
    */
    'wins' = undefined;
    /**
    * Stage 1 wins
    * @member {Number} stage_1_wins
    */
    'stage_1_wins' = undefined;
    /**
    * Stage 2 wins
    * @member {Number} stage_2_wins
    */
    'stage_2_wins' = undefined;
    /**
    * Stage 3 wins
    * @member {Number} stage_3_wins
    */
    'stage_3_wins' = undefined;
    /**
    * Total stage points
    * @member {Number} stage_points
    */
    'stage_points' = undefined;
    /**
    * Playoff race wins
    * @member {Number} playoff_race_wins
    */
    'playoff_race_wins' = undefined;
    /**
    * Playoff stage wins
    * @member {Number} playoff_stage_wins
    */
    'playoff_stage_wins' = undefined;
    /**
    * Points earned this race
    * @member {Number} points_earned_this_race
    */
    'points_earned_this_race' = undefined;
    /**
    * Playoff points earned this race
    * @member {Number} playoff_points_earned_this_race
    */
    'playoff_points_earned_this_race' = undefined;
    /**
    * Stage points earned this race
    * @member {Number} stage_points_earned_this_race
    */
    'stage_points_earned_this_race' = undefined;
    /**
    * Number of Top 5 finishes
    * @member {Number} top5
    */
    'top5' = undefined;
    /**
    * Number of Top 10 finishes
    * @member {Number} top10
    */
    'top10' = undefined;
    /**
    * Total laps led
    * @member {Number} laps_led
    */
    'laps_led' = undefined;
    /**
    * Number of times the vehicle did not finish the race
    * @member {Number} dnf
    */
    'dnf' = undefined;
    /**
    * Whether or not the owner made the playoffs
    * @member {Boolean} made_playoffs
    */
    'made_playoffs' = undefined;
    /**
    * Whether or not the owner is still in the playoffs
    * @member {Boolean} in_playoffs
    */
    'in_playoffs' = undefined;
    /**
    * Highest playoff round earned
    * @member {Number} highest_round
    */
    'highest_round' = undefined;




}
