/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Pitstop model module.
* @module model/Pitstop
* @version 1.0
*/
export default class Pitstop {
    /**
    * Constructs a new <code>Pitstop</code>.
    * @alias module:model/Pitstop
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Pitstop</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Pitstop} obj Optional instance to populate.
    * @return {module:model/Pitstop} The populated <code>Pitstop</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pitstop();
                        
            
            if (data.hasOwnProperty('lap')) {
                obj['lap'] = ApiClient.convertToType(data['lap'], 'Number');
            }
            if (data.hasOwnProperty('leader_lap')) {
                obj['leader_lap'] = ApiClient.convertToType(data['leader_lap'], 'Number');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('enter_flagstate')) {
                obj['enter_flagstate'] = ApiClient.convertToType(data['enter_flagstate'], 'Number');
            }
            if (data.hasOwnProperty('enter_racetime')) {
                obj['enter_racetime'] = ApiClient.convertToType(data['enter_racetime'], 'Number');
            }
            if (data.hasOwnProperty('enter_travelduration')) {
                obj['enter_travelduration'] = ApiClient.convertToType(data['enter_travelduration'], 'Number');
            }
            if (data.hasOwnProperty('adjustment_left')) {
                obj['adjustment_left'] = ApiClient.convertToType(data['adjustment_left'], 'Boolean');
            }
            if (data.hasOwnProperty('adjustment_right')) {
                obj['adjustment_right'] = ApiClient.convertToType(data['adjustment_right'], 'Boolean');
            }
            if (data.hasOwnProperty('body_repairs')) {
                obj['body_repairs'] = ApiClient.convertToType(data['body_repairs'], 'Boolean');
            }
            if (data.hasOwnProperty('fuel_cans')) {
                obj['fuel_cans'] = ApiClient.convertToType(data['fuel_cans'], 'Number');
            }
            if (data.hasOwnProperty('leftfront_tirechanged')) {
                obj['leftfront_tirechanged'] = ApiClient.convertToType(data['leftfront_tirechanged'], 'Boolean');
            }
            if (data.hasOwnProperty('Leftrear_tirechanged')) {
                obj['Leftrear_tirechanged'] = ApiClient.convertToType(data['Leftrear_tirechanged'], 'Boolean');
            }
            if (data.hasOwnProperty('rightfront_tirechanged')) {
                obj['rightfront_tirechanged'] = ApiClient.convertToType(data['rightfront_tirechanged'], 'Boolean');
            }
            if (data.hasOwnProperty('rightrear_tirechanged')) {
                obj['rightrear_tirechanged'] = ApiClient.convertToType(data['rightrear_tirechanged'], 'Boolean');
            }
            if (data.hasOwnProperty('infraction')) {
                obj['infraction'] = ApiClient.convertToType(data['infraction'], 'String');
            }
            if (data.hasOwnProperty('video')) {
                obj['video'] = ApiClient.convertToType(data['video'], 'String');
            }
            if (data.hasOwnProperty('pitbox_enter')) {
                obj['pitbox_enter'] = ApiClient.convertToType(data['pitbox_enter'], 'Number');
            }
            if (data.hasOwnProperty('pitbox_exit')) {
                obj['pitbox_exit'] = ApiClient.convertToType(data['pitbox_exit'], 'Number');
            }
            if (data.hasOwnProperty('exit_flagstate')) {
                obj['exit_flagstate'] = ApiClient.convertToType(data['exit_flagstate'], 'Number');
            }
            if (data.hasOwnProperty('exit_racetime')) {
                obj['exit_racetime'] = ApiClient.convertToType(data['exit_racetime'], 'Number');
            }
            if (data.hasOwnProperty('exit_travelduration')) {
                obj['exit_travelduration'] = ApiClient.convertToType(data['exit_travelduration'], 'Number');
            }
            if (data.hasOwnProperty('total_duration')) {
                obj['total_duration'] = ApiClient.convertToType(data['total_duration'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Lap
    * @member {Number} lap
    */
    'lap' = undefined;
    /**
    * Leader lap
    * @member {Number} leader_lap
    */
    'leader_lap' = undefined;
    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * Enter flag state
    * @member {Number} enter_flagstate
    */
    'enter_flagstate' = undefined;
    /**
    * Exit flag state
    * @member {Number} enter_racetime
    */
    'enter_racetime' = undefined;
    /**
    * Enter travel duration
    * @member {Number} enter_travelduration
    */
    'enter_travelduration' = undefined;
    /**
    * Adjustment left
    * @member {Boolean} adjustment_left
    */
    'adjustment_left' = undefined;
    /**
    * Adjustment right
    * @member {Boolean} adjustment_right
    */
    'adjustment_right' = undefined;
    /**
    * Body repairs
    * @member {Boolean} body_repairs
    */
    'body_repairs' = undefined;
    /**
    * Number of fuel cans
    * @member {Number} fuel_cans
    */
    'fuel_cans' = undefined;
    /**
    * Left front tire changed
    * @member {Boolean} leftfront_tirechanged
    */
    'leftfront_tirechanged' = undefined;
    /**
    * Left rear tire changed
    * @member {Boolean} Leftrear_tirechanged
    */
    'Leftrear_tirechanged' = undefined;
    /**
    * Right front tire changed
    * @member {Boolean} rightfront_tirechanged
    */
    'rightfront_tirechanged' = undefined;
    /**
    * Right rear tire changed
    * @member {Boolean} rightrear_tirechanged
    */
    'rightrear_tirechanged' = undefined;
    /**
    * Infraction
    * @member {String} infraction
    */
    'infraction' = undefined;
    /**
    * Video
    * @member {String} video
    */
    'video' = undefined;
    /**
    * Pit box enter
    * @member {Number} pitbox_enter
    */
    'pitbox_enter' = undefined;
    /**
    * Pit box exit
    * @member {Number} pitbox_exit
    */
    'pitbox_exit' = undefined;
    /**
    * Exit flag state
    * @member {Number} exit_flagstate
    */
    'exit_flagstate' = undefined;
    /**
    * Exit race time
    * @member {Number} exit_racetime
    */
    'exit_racetime' = undefined;
    /**
    * Exit travel duration
    * @member {Number} exit_travelduration
    */
    'exit_travelduration' = undefined;
    /**
    * Total duration
    * @member {Number} total_duration
    */
    'total_duration' = undefined;




}
