/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The ProcessingState model module.
* @module model/ProcessingState
* @version 1.0
*/
export default class ProcessingState {
    /**
    * Constructs a new <code>ProcessingState</code>.
    * @alias module:model/ProcessingState
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ProcessingState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProcessingState} obj Optional instance to populate.
    * @return {module:model/ProcessingState} The populated <code>ProcessingState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessingState();
                        
            
            if (data.hasOwnProperty('Category')) {
                obj['Category'] = ApiClient.convertToType(data['Category'], 'String');
            }
            if (data.hasOwnProperty('IntervalInSeconds')) {
                obj['IntervalInSeconds'] = ApiClient.convertToType(data['IntervalInSeconds'], 'Number');
            }
            if (data.hasOwnProperty('Action')) {
                obj['Action'] = ApiClient.convertToType(data['Action'], 'String');
            }
            if (data.hasOwnProperty('LastRun')) {
                obj['LastRun'] = ApiClient.convertToType(data['LastRun'], 'Date');
            }
            if (data.hasOwnProperty('ActionDetailId')) {
                obj['ActionDetailId'] = ApiClient.convertToType(data['ActionDetailId'], 'Number');
            }
            if (data.hasOwnProperty('Value')) {
                obj['Value'] = ApiClient.convertToType(data['Value'], 'Number');
            }
            if (data.hasOwnProperty('IsActive')) {
                obj['IsActive'] = ApiClient.convertToType(data['IsActive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} Category
    */
    'Category' = undefined;
    /**
    * @member {Number} IntervalInSeconds
    */
    'IntervalInSeconds' = undefined;
    /**
    * @member {String} Action
    */
    'Action' = undefined;
    /**
    * @member {Date} LastRun
    */
    'LastRun' = undefined;
    /**
    * @member {Number} ActionDetailId
    */
    'ActionDetailId' = undefined;
    /**
    * @member {Number} Value
    */
    'Value' = undefined;
    /**
    * @member {Boolean} IsActive
    */
    'IsActive' = undefined;




}
