/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
/**
* Enum class PublishState.
* @enum {}
* @readonly
*/
export default class PublishState {
        /**
         * value: 0
         * @const
         */
        0 = 0;

        /**
         * value: 1
         * @const
         */
        1 = 1;

        /**
         * value: 2
         * @const
         */
        2 = 2;

        /**
         * value: 3
         * @const
         */
        3 = 3;


    /**
    * Returns a <code>PublishState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PublishState} The enum <code>PublishState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
