/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import RunResult from './RunResult.js';

/**
* The QualifyingRunResults model module.
* @module model/QualifyingRunResults
* @version 1.0
*/
export default class QualifyingRunResults {
    /**
    * Constructs a new <code>QualifyingRunResults</code>.
    * @alias module:model/QualifyingRunResults
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>QualifyingRunResults</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/QualifyingRunResults} obj Optional instance to populate.
    * @return {module:model/QualifyingRunResults} The populated <code>QualifyingRunResults</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QualifyingRunResults();
                        
            
            if (data.hasOwnProperty('run_name')) {
                obj['run_name'] = ApiClient.convertToType(data['run_name'], 'String');
            }
            if (data.hasOwnProperty('run_state')) {
                obj['run_state'] = ApiClient.convertToType(data['run_state'], 'String');
            }
            if (data.hasOwnProperty('flag_state')) {
                obj['flag_state'] = ApiClient.convertToType(data['flag_state'], 'String');
            }
            if (data.hasOwnProperty('round')) {
                obj['round'] = ApiClient.convertToType(data['round'], 'Number');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [RunResult]);
            }
        }
        return obj;
    }

    /**
    * Run name
    * @member {String} run_name
    */
    'run_name' = undefined;
    /**
    * Run state:  (Inactive, Active, Completed)
    * @member {String} run_state
    */
    'run_state' = undefined;
    /**
    * Flag state:  (NONE, WARMUP, GREEN, YELLOW, RED, WHITE, FINISH, EXTRA)
    * @member {String} flag_state
    */
    'flag_state' = undefined;
    /**
    * Qualifying round: 0-3
    * @member {Number} round
    */
    'round' = undefined;
    /**
    * Qualifying group: A, B, (empty)
    * @member {String} group
    */
    'group' = undefined;
    /**
    * Qualifying results
    * @member {Array.<module:model/RunResult>} results
    */
    'results' = undefined;




}
