/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The RosterMember model module.
* @module model/RosterMember
* @version 1.0
*/
export default class RosterMember {
    /**
    * Constructs a new <code>RosterMember</code>.
    * @alias module:model/RosterMember
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RosterMember</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RosterMember} obj Optional instance to populate.
    * @return {module:model/RosterMember} The populated <code>RosterMember</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RosterMember();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
        }
        return obj;
    }

    /**
    * Team member name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Position
    * @member {String} position
    */
    'position' = undefined;




}
