/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Flag from './Flag.js';
import RunState from './RunState.js';
import RunType from './RunType.js';

/**
* The RunDetails model module.
* @module model/RunDetails
* @version 1.0
*/
export default class RunDetails {
    /**
    * Constructs a new <code>RunDetails</code>.
    * @alias module:model/RunDetails
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RunDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RunDetails} obj Optional instance to populate.
    * @return {module:model/RunDetails} The populated <code>RunDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunDetails();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('run_state')) {
                obj['run_state'] = RunState.constructFromObject(data['run_state']);
            }
            if (data.hasOwnProperty('run_type')) {
                obj['run_type'] = RunType.constructFromObject(data['run_type']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('flag_state')) {
                obj['flag_state'] = ApiClient.convertToType(data['flag_state'], 'String');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], [Flag]);
            }
        }
        return obj;
    }

    /**
    * The name of the run
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Scheduled start time
    * @member {Date} start_time
    */
    'start_time' = undefined;
    /**
    * @member {module:model/RunState} run_state
    */
    'run_state' = undefined;
    /**
    * @member {module:model/RunType} run_type
    */
    'run_type' = undefined;
    /**
    * The scheduled duration of the run in seconds
    * @member {Number} duration
    */
    'duration' = undefined;
    /**
    * Flag state:  (Inactive, Active, Completed)
    * @member {String} flag_state
    */
    'flag_state' = undefined;
    /**
    * Flags associated with this run
    * @member {Array.<module:model/Flag>} flags
    */
    'flags' = undefined;




}
