/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The RunEntry model module.
* @module model/RunEntry
* @version 1.0
*/
export default class RunEntry {
    /**
    * Constructs a new <code>RunEntry</code>.
    * @alias module:model/RunEntry
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RunEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RunEntry} obj Optional instance to populate.
    * @return {module:model/RunEntry} The populated <code>RunEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunEntry();
                        
            
            if (data.hasOwnProperty('driver_name')) {
                obj['driver_name'] = ApiClient.convertToType(data['driver_name'], 'String');
            }
            if (data.hasOwnProperty('driver_details')) {
                obj['driver_details'] = ApiClient.convertToType(data['driver_details'], 'String');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('vehicle_details')) {
                obj['vehicle_details'] = ApiClient.convertToType(data['vehicle_details'], 'String');
            }
            if (data.hasOwnProperty('owner_name')) {
                obj['owner_name'] = ApiClient.convertToType(data['owner_name'], 'String');
            }
            if (data.hasOwnProperty('crew_chief')) {
                obj['crew_chief'] = ApiClient.convertToType(data['crew_chief'], 'String');
            }
            if (data.hasOwnProperty('model_year')) {
                obj['model_year'] = ApiClient.convertToType(data['model_year'], 'Number');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
        }
        return obj;
    }

    /**
    * Driver name
    * @member {String} driver_name
    */
    'driver_name' = undefined;
    /**
    * URL to driver details
    * @member {String} driver_details
    */
    'driver_details' = undefined;
    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * URL to vehicle details
    * @member {String} vehicle_details
    */
    'vehicle_details' = undefined;
    /**
    * Owner name
    * @member {String} owner_name
    */
    'owner_name' = undefined;
    /**
    * Crew chief name
    * @member {String} crew_chief
    */
    'crew_chief' = undefined;
    /**
    * Vehicle model year
    * @member {Number} model_year
    */
    'model_year' = undefined;
    /**
    * Vehicle model
    * @member {String} model
    */
    'model' = undefined;




}
