/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The RunResult model module.
* @module model/RunResult
* @version 1.0
*/
export default class RunResult {
    /**
    * Constructs a new <code>RunResult</code>.
    * @alias module:model/RunResult
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RunResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RunResult} obj Optional instance to populate.
    * @return {module:model/RunResult} The populated <code>RunResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunResult();
                        
            
            if (data.hasOwnProperty('finish_position')) {
                obj['finish_position'] = ApiClient.convertToType(data['finish_position'], 'Number');
            }
            if (data.hasOwnProperty('driver_name')) {
                obj['driver_name'] = ApiClient.convertToType(data['driver_name'], 'String');
            }
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('laps')) {
                obj['laps'] = ApiClient.convertToType(data['laps'], 'Number');
            }
            if (data.hasOwnProperty('best_time')) {
                obj['best_time'] = ApiClient.convertToType(data['best_time'], 'Number');
            }
            if (data.hasOwnProperty('best_speed')) {
                obj['best_speed'] = ApiClient.convertToType(data['best_speed'], 'Number');
            }
            if (data.hasOwnProperty('best_lap')) {
                obj['best_lap'] = ApiClient.convertToType(data['best_lap'], 'Number');
            }
            if (data.hasOwnProperty('last_lap_time')) {
                obj['last_lap_time'] = ApiClient.convertToType(data['last_lap_time'], 'Number');
            }
            if (data.hasOwnProperty('delta_next_time')) {
                obj['delta_next_time'] = ApiClient.convertToType(data['delta_next_time'], 'Number');
            }
            if (data.hasOwnProperty('delta_next_laps')) {
                obj['delta_next_laps'] = ApiClient.convertToType(data['delta_next_laps'], 'Number');
            }
            if (data.hasOwnProperty('delta_leader_time')) {
                obj['delta_leader_time'] = ApiClient.convertToType(data['delta_leader_time'], 'Number');
            }
            if (data.hasOwnProperty('delta_leader_laps')) {
                obj['delta_leader_laps'] = ApiClient.convertToType(data['delta_leader_laps'], 'Number');
            }
            if (data.hasOwnProperty('on_track')) {
                obj['on_track'] = ApiClient.convertToType(data['on_track'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }

    /**
    * Finish position
    * @member {Number} finish_position
    */
    'finish_position' = undefined;
    /**
    * Driver name
    * @member {String} driver_name
    */
    'driver_name' = undefined;
    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * Number of laps
    * @member {Number} laps
    */
    'laps' = undefined;
    /**
    * Best lap time in milliseconds
    * @member {Number} best_time
    */
    'best_time' = undefined;
    /**
    * Best speed in MPH
    * @member {Number} best_speed
    */
    'best_speed' = undefined;
    /**
    * Best lap number
    * @member {Number} best_lap
    */
    'best_lap' = undefined;
    /**
    * Last lap time
    * @member {Number} last_lap_time
    */
    'last_lap_time' = undefined;
    /**
    * Number of milliseconds behind the next position
    * @member {Number} delta_next_time
    */
    'delta_next_time' = undefined;
    /**
    * Number of laps behind the next position
    * @member {Number} delta_next_laps
    */
    'delta_next_laps' = undefined;
    /**
    * Number of milliseconds behind the leader
    * @member {Number} delta_leader_time
    */
    'delta_leader_time' = undefined;
    /**
    * Number of laps behind the leader
    * @member {Number} delta_leader_laps
    */
    'delta_leader_laps' = undefined;
    /**
    * Is on track
    * @member {Boolean} on_track
    */
    'on_track' = undefined;
    /**
    * Status
    * @member {String} status
    */
    'status' = undefined;
    /**
    * Comment
    * @member {String} comment
    */
    'comment' = undefined;




}
