/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
/**
* Enum class RunType.
* @enum {}
* @readonly
*/
export default class RunType {
        /**
         * value: "Practice"
         * @const
         */
        Practice = "Practice";

        /**
         * value: "Qualifying"
         * @const
         */
        Qualifying = "Qualifying";

        /**
         * value: "Race"
         * @const
         */
        Race = "Race";


    /**
    * Returns a <code>RunType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RunType} The enum <code>RunType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
