/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Series model module.
* @module model/Series
* @version 1.0
*/
export default class Series {
    /**
    * Constructs a new <code>Series</code>.
    * @alias module:model/Series
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Series</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Series} obj Optional instance to populate.
    * @return {module:model/Series} The populated <code>Series</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Series();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('short_name')) {
                obj['short_name'] = ApiClient.convertToType(data['short_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = ApiClient.convertToType(data['abbreviation'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
        }
        return obj;
    }

    /**
    * The series id
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * Series short name
    * @member {String} short_name
    */
    'short_name' = undefined;
    /**
    * Series full name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Series abbreviation
    * @member {String} abbreviation
    */
    'abbreviation' = undefined;
    /**
    * URL to series logo
    * @member {String} logo
    */
    'logo' = undefined;




}
