/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import StageResult from './StageResult.js';

/**
* The StageRunResults model module.
* @module model/StageRunResults
* @version 1.0
*/
export default class StageRunResults {
    /**
    * Constructs a new <code>StageRunResults</code>.
    * @alias module:model/StageRunResults
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>StageRunResults</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StageRunResults} obj Optional instance to populate.
    * @return {module:model/StageRunResults} The populated <code>StageRunResults</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StageRunResults();
                        
            
            if (data.hasOwnProperty('stage_number')) {
                obj['stage_number'] = ApiClient.convertToType(data['stage_number'], 'Number');
            }
            if (data.hasOwnProperty('stage_name')) {
                obj['stage_name'] = ApiClient.convertToType(data['stage_name'], 'String');
            }
            if (data.hasOwnProperty('lap')) {
                obj['lap'] = ApiClient.convertToType(data['lap'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [StageResult]);
            }
        }
        return obj;
    }

    /**
    * Stage number
    * @member {Number} stage_number
    */
    'stage_number' = undefined;
    /**
    * Stage name
    * @member {String} stage_name
    */
    'stage_name' = undefined;
    /**
    * The lap when the stage occurred
    * @member {Number} lap
    */
    'lap' = undefined;
    /**
    * Stage results
    * @member {Array.<module:model/StageResult>} results
    */
    'results' = undefined;




}
