/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RosterMember from './RosterMember';

/**
* The TeamRoster model module.
* @module model/TeamRoster
* @version 1.0
*/
export default class TeamRoster {
    /**
    * Constructs a new <code>TeamRoster</code>.
    * @alias module:model/TeamRoster
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TeamRoster</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TeamRoster} obj Optional instance to populate.
    * @return {module:model/TeamRoster} The populated <code>TeamRoster</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamRoster();
                        
            
            if (data.hasOwnProperty('vehicle_number')) {
                obj['vehicle_number'] = ApiClient.convertToType(data['vehicle_number'], 'String');
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [RosterMember]);
            }
        }
        return obj;
    }

    /**
    * Vehicle number
    * @member {String} vehicle_number
    */
    'vehicle_number' = undefined;
    /**
    * Team members
    * @member {Array.<module:model/RosterMember>} members
    */
    'members' = undefined;




}
