/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TokenResponse model module.
* @module model/TokenResponse
* @version 1.0
*/
export default class TokenResponse {
    /**
    * Constructs a new <code>TokenResponse</code>.
    * @alias module:model/TokenResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TokenResponse} obj Optional instance to populate.
    * @return {module:model/TokenResponse} The populated <code>TokenResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenResponse();
                        
            
            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} access_token
    */
    'access_token' = undefined;
    /**
    * @member {String} refresh_token
    */
    'refresh_token' = undefined;
    /**
    * @member {String} token_type
    */
    'token_type' = undefined;




}
