/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The WeekendSchedule model module.
* @module model/WeekendSchedule
* @version 1.0
*/
export default class WeekendSchedule {
    /**
    * Constructs a new <code>WeekendSchedule</code>.
    * @alias module:model/WeekendSchedule
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WeekendSchedule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WeekendSchedule} obj Optional instance to populate.
    * @return {module:model/WeekendSchedule} The populated <code>WeekendSchedule</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WeekendSchedule();
                        
            
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The name of the activity
    * @member {String} activity
    */
    'activity' = undefined;
    /**
    * Scheduled start time
    * @member {Date} start_time
    */
    'start_time' = undefined;
    /**
    * Scheduled end time (if any)
    * @member {Date} end_time
    */
    'end_time' = undefined;




}
