/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js";
import DriverSummary from '../model/DriverSummary.js';

/**
* DriverSummary service.
* @module api/DriverSummaryApi
* @version 1.0
*/
export default class DriverSummaryApi {

    /**
    * Constructs a new DriverSummaryApi. 
    * @alias module:api/DriverSummaryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the driverSummaryGet operation.
     * @callback module:api/DriverSummaryApi~driverSummaryGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DriverSummary>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/DriverSummaryApi~driverSummaryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DriverSummary>}
     */
    driverSummaryGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'series_id': opts['seriesId'],
        'season': opts['season'],
        'driver_id': opts['driverId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [DriverSummary];

      return this.apiClient.callApi(
        '/driver-summary', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
