/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js";
import OSSScan from '../model/OSSScan.js';
import VehicleWeight from '../model/VehicleWeight.js';

/**
* Inspections service.
* @module api/InspectionsApi
* @version 1.0
*/
export default class InspectionsApi {

    /**
    * Constructs a new InspectionsApi. 
    * @alias module:api/InspectionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the inspectionsOssGet operation.
     * @callback module:api/InspectionsApi~inspectionsOssGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/OSSScan>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/InspectionsApi~inspectionsOssGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/OSSScan>}
     */
    inspectionsOssGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'race_id': opts['raceId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [OSSScan];

      return this.apiClient.callApi(
        '/inspections/oss', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the inspectionsVehicleWeightsGet operation.
     * @callback module:api/InspectionsApi~inspectionsVehicleWeightsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleWeight>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/InspectionsApi~inspectionsVehicleWeightsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleWeight>}
     */
    inspectionsVehicleWeightsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'race_id': opts['raceId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [VehicleWeight];

      return this.apiClient.callApi(
        '/inspections/vehicle-weights', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
