/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.DisciplineUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DisciplineUpdate', function() {
    it('should create an instance of DisciplineUpdate', function() {
      // uncomment below and update the code to test DisciplineUpdate
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be.a(NascarDataClient.DisciplineUpdate);
    });

    it('should have the property inspectionType (base name: "inspection_type")', function() {
      // uncomment below and update the code to test the property inspectionType
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be();
    });

    it('should have the property discipline (base name: "discipline")', function() {
      // uncomment below and update the code to test the property discipline
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vehicleNumber (base name: "vehicle_number")', function() {
      // uncomment below and update the code to test the property vehicleNumber
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be();
    });

    it('should have the property chassis (base name: "chassis")', function() {
      // uncomment below and update the code to test the property chassis
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be();
    });

    it('should have the property inspectionTime (base name: "inspection_time")', function() {
      // uncomment below and update the code to test the property inspectionTime
      //var instane = new NascarDataClient.DisciplineUpdate();
      //expect(instance).to.be();
    });

  });

}));
