/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.DriverSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DriverSummary', function() {
    it('should create an instance of DriverSummary', function() {
      // uncomment below and update the code to test DriverSummary
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be.a(NascarDataClient.DriverSummary);
    });

    it('should have the property driver (base name: "Driver")', function() {
      // uncomment below and update the code to test the property driver
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be();
    });

    it('should have the property summaryByPrincipalRaceIDs (base name: "Summary_ByPrincipalRaceIDs")', function() {
      // uncomment below and update the code to test the property summaryByPrincipalRaceIDs
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be();
    });

    it('should have the property summaryBySeason (base name: "Summary_BySeason")', function() {
      // uncomment below and update the code to test the property summaryBySeason
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be();
    });

    it('should have the property summaryByTracks (base name: "Summary_ByTracks")', function() {
      // uncomment below and update the code to test the property summaryByTracks
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be();
    });

    it('should have the property summaryByTrackTypes (base name: "Summary_ByTrackTypes")', function() {
      // uncomment below and update the code to test the property summaryByTrackTypes
      //var instane = new NascarDataClient.DriverSummary();
      //expect(instance).to.be();
    });

  });

}));
