/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.QualifyingRunResults();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QualifyingRunResults', function() {
    it('should create an instance of QualifyingRunResults', function() {
      // uncomment below and update the code to test QualifyingRunResults
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be.a(NascarDataClient.QualifyingRunResults);
    });

    it('should have the property runName (base name: "run_name")', function() {
      // uncomment below and update the code to test the property runName
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

    it('should have the property runState (base name: "run_state")', function() {
      // uncomment below and update the code to test the property runState
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

    it('should have the property flagState (base name: "flag_state")', function() {
      // uncomment below and update the code to test the property flagState
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

    it('should have the property round (base name: "round")', function() {
      // uncomment below and update the code to test the property round
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

    it('should have the property results (base name: "results")', function() {
      // uncomment below and update the code to test the property results
      //var instane = new NascarDataClient.QualifyingRunResults();
      //expect(instance).to.be();
    });

  });

}));
