/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.RaceInfraction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RaceInfraction', function() {
    it('should create an instance of RaceInfraction', function() {
      // uncomment below and update the code to test RaceInfraction
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be.a(NascarDataClient.RaceInfraction);
    });

    it('should have the property flagState (base name: "flag_state")', function() {
      // uncomment below and update the code to test the property flagState
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property infraction (base name: "infraction")', function() {
      // uncomment below and update the code to test the property infraction
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property vehicleNumber (base name: "vehicle_number")', function() {
      // uncomment below and update the code to test the property vehicleNumber
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property lap (base name: "lap")', function() {
      // uncomment below and update the code to test the property lap
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property lapAssessed (base name: "lap_assessed")', function() {
      // uncomment below and update the code to test the property lapAssessed
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property timeOfRace (base name: "time_of_race")', function() {
      // uncomment below and update the code to test the property timeOfRace
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property penalty (base name: "penalty")', function() {
      // uncomment below and update the code to test the property penalty
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instane = new NascarDataClient.RaceInfraction();
      //expect(instance).to.be();
    });

  });

}));
