/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.RaceWeek();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RaceWeek', function() {
    it('should create an instance of RaceWeek', function() {
      // uncomment below and update the code to test RaceWeek
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be.a(NascarDataClient.RaceWeek);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property season (base name: "season")', function() {
      // uncomment below and update the code to test the property season
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property venue (base name: "venue")', function() {
      // uncomment below and update the code to test the property venue
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property runningSeries (base name: "running_series")', function() {
      // uncomment below and update the code to test the property runningSeries
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "end_date")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property isLive (base name: "is_live")', function() {
      // uncomment below and update the code to test the property isLive
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

    it('should have the property details (base name: "details")', function() {
      // uncomment below and update the code to test the property details
      //var instane = new NascarDataClient.RaceWeek();
      //expect(instance).to.be();
    });

  });

}));
