/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.RaceResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RaceResult', function() {
    it('should create an instance of RaceResult', function() {
      // uncomment below and update the code to test RaceResult
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be.a(NascarDataClient.RaceResult);
    });

    it('should have the property finishPosition (base name: "finish_position")', function() {
      // uncomment below and update the code to test the property finishPosition
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property driverName (base name: "driver_name")', function() {
      // uncomment below and update the code to test the property driverName
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property vehicleNumber (base name: "vehicle_number")', function() {
      // uncomment below and update the code to test the property vehicleNumber
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property laps (base name: "laps")', function() {
      // uncomment below and update the code to test the property laps
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property bestTime (base name: "best_time")', function() {
      // uncomment below and update the code to test the property bestTime
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property bestSpeed (base name: "best_speed")', function() {
      // uncomment below and update the code to test the property bestSpeed
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property bestLap (base name: "best_lap")', function() {
      // uncomment below and update the code to test the property bestLap
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property lastLapTime (base name: "last_lap_time")', function() {
      // uncomment below and update the code to test the property lastLapTime
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property deltaNextTime (base name: "delta_next_time")', function() {
      // uncomment below and update the code to test the property deltaNextTime
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property deltaNextLaps (base name: "delta_next_laps")', function() {
      // uncomment below and update the code to test the property deltaNextLaps
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property deltaLeaderTime (base name: "delta_leader_time")', function() {
      // uncomment below and update the code to test the property deltaLeaderTime
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property deltaLeaderLaps (base name: "delta_leader_laps")', function() {
      // uncomment below and update the code to test the property deltaLeaderLaps
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property onTrack (base name: "on_track")', function() {
      // uncomment below and update the code to test the property onTrack
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

    it('should have the property startPosition (base name: "start_position")', function() {
      // uncomment below and update the code to test the property startPosition
      //var instane = new NascarDataClient.RaceResult();
      //expect(instance).to.be();
    });

  });

}));
