/**
 * NASCAR.Data.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NascarDataClient);
  }
}(this, function(expect, NascarDataClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NascarDataClient.VehicleWeight();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleWeight', function() {
    it('should create an instance of VehicleWeight', function() {
      // uncomment below and update the code to test VehicleWeight
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be.a(NascarDataClient.VehicleWeight);
    });

    it('should have the property inspectionType (base name: "inspection_type")', function() {
      // uncomment below and update the code to test the property inspectionType
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property vehicleNumber (base name: "vehicle_number")', function() {
      // uncomment below and update the code to test the property vehicleNumber
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property adjustment (base name: "adjustment")', function() {
      // uncomment below and update the code to test the property adjustment
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property crossWeight (base name: "cross_weight")', function() {
      // uncomment below and update the code to test the property crossWeight
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property leftFront (base name: "left_front")', function() {
      // uncomment below and update the code to test the property leftFront
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property leftRear (base name: "left_rear")', function() {
      // uncomment below and update the code to test the property leftRear
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property leftSide (base name: "left_side")', function() {
      // uncomment below and update the code to test the property leftSide
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property nose (base name: "nose")', function() {
      // uncomment below and update the code to test the property nose
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property rear (base name: "rear")', function() {
      // uncomment below and update the code to test the property rear
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property rightFront (base name: "right_front")', function() {
      // uncomment below and update the code to test the property rightFront
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property rightRear (base name: "right_rear")', function() {
      // uncomment below and update the code to test the property rightRear
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property rightSide (base name: "right_side")', function() {
      // uncomment below and update the code to test the property rightSide
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property totalWeight (base name: "total_weight")', function() {
      // uncomment below and update the code to test the property totalWeight
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

    it('should have the property passed (base name: "passed")', function() {
      // uncomment below and update the code to test the property passed
      //var instane = new NascarDataClient.VehicleWeight();
      //expect(instance).to.be();
    });

  });

}));
